APACHE_DOCROOT_IN_REPO       
CARGO_HOME                   
EDITOR                       
GEM_HOME                     
GEM_PATH                     
GITPOD_ANALYTICS_SEGMENT_KEY 
GITPOD_ANALYTICS_WRITER      
GITPOD_CLI_APITOKEN          
GITPOD_GIT_USER_EMAIL        
GITPOD_GIT_USER_NAME         
GITPOD_HOST                  
GITPOD_IDE_ALIAS             
GITPOD_INSTANCE_ID           
GITPOD_INTERVAL              
GITPOD_MEMORY                
GITPOD_OWNER_ID              
GITPOD_PREVENT_METADATA_ACCES
GITPOD_REPO_ROOT             
GITPOD_REPO_ROOTS            
GITPOD_THEIA_PORT            
GITPOD_WORKSPACE_CLASS       
GITPOD_WORKSPACE_CLASS_INFO
GITPOD_WORKSPACE_CLUSTER_HOST
GITPOD_WORKSPACE_CONTEXT      
GITPOD_WORKSPACE_CONTEXT_URL 
GITPOD_WORKSPACE_ID          
GITPOD_WORKSPACE_URL         
GIT_EDITOR                   
GOPATH                       
GOROOT                        
GO_VERSION                    
GP_EXTERNAL_BROWSER           
GP_OPEN_EDITOR                
GP_PREVIEW_BROWSER            
GP_PYENV_FAKEROOT             
GP_PYENV_INIT                 
GP_PYENV_MIRROR               
GRADLE_HOME                   
GRADLE_USER_HOME              
HOME                          
HOMEBREW_NO_AUTO_UPDATE       
HOSTNAME                      
INFOPATH                      
IRBRC                         
JAVA_HOME                     
JAVA_TOOL_OPTIONS             
LANG                          
LESSCLOSE                     
LESSOPEN                      
LS_COLORS                        
MANPATH                         
MAVEN_HOME                      
MY_RUBY_HOME                    
NGINX_DOCROOT_IN_REPO           
NIX_PROFILES                    
NIX_SSL_CERT_FILE               
NIX_VERSION                     
NODE_VERSION                    
NVM_DIR                         
PATH                            
PIPENV_VENV_IN_PROJECT          
PIP_CACHE_DIR                   
POETRY_CACHE_DIR                
PWD                             
PYENV_HOOK_PATH                 
PYENV_ROOT                      
PYENV_SHELL                     
PYENV_VIRTUALENV_INIT           
PYTHONUSERBASE                  
PYTHONUSERBASE_VERSION_FILE     
RUBY_VERSION                    
SDKMAN_CANDIDATES_API           
SDKMAN_CANDIDATES_DIR           
SDKMAN_DIR                      
SDKMAN_PLATFORM                 
SDKMAN_VERSION                  
SHLVL                           
SUPERVISOR_ADDR                 
TERM                            
THEIA_MINI_BROWSER_HOST_PATTERN 
THEIA_RATELIMIT_LOG             
THEIA_WEBVIEW_EXTERNAL_ENDPOINT 
THEIA_WORKSPACE_ROOT            
TRIGGER_REBUILD                 
USER                            
VISUAL                          
VSX_REGISTRY_URL                
WORKSPACEKIT_WRAP_NETNS         
_                               
rvm_bin_path                    
rvm_path                        
rvm_prefix                      
rvm_version                     